name: Deploy Development

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ridwanray
          POSTGRES_PASSWORD: db_password
          POSTGRES_DB: test_database_name
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python 3.10.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements/dev.txt

    - name: Run migrations
      env:
          DATABASE_URL: postgres://ridwanray:db_password@localhost/test_database_name
          SECRET_KEY: a_standard_secret
      run: |
        python app/manage.py makemigrations
        python app/manage.py migrate

    - name: Run Tests
      env:
          DEBUG: 0
          DATABASE_URL: postgres://ridwanray:db_password@localhost/test_database_name
          SENDER_EMAIL: hi@ridwanray.com
          SECRET_KEY: standard_secret_key
      run: |
        cd app
        pytest -n auto
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        USERNAME: ${{ secrets.DEV_USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.DEV_SSHKEY }}
        script: cd ${{ secrets.DEV_PATH }} && ls && git pull && docker compose up --build -d
